import { Inter,Outfit } from "next/font/google";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import "./globals.css";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang='en'>
      <body>
        <SignedOut>
        </SignedOut>
        <SignedIn>
        </SignedIn>
        {children}
      </body>
    </html>
  </ClerkProvider>
  );
}
